services:
    redis:
      image: 'redis:latest'
      
      container_name: redis


    price-service-tg-bot:
        container_name: task-service

        build: .

        volumes:
          - task-service-volume:/task-service/logs

        network_mode: container:redis

        depends_on:
          - redis


volumes:
    task-service-volume:
        name: task-service-logs