services:
    redis:
      image: 'redis:latest'
      
      container_name: redis

      ports:
          - 8080:8080


    task-service:
        container_name: task-service

        build: .

        volumes:
          - task-service-volume:/task_service/logs

        network_mode: container:redis

        depends_on:
          - redis


volumes:
    task-service-volume:
        name: task-service-logs